function paths = get_gec_paths()
%GET_GEC_PATHS Centralised paths for the ADNI3 GEC pipeline.
%
% Edit only this file if the project is moved to another machine.

paths = struct();

% -------------------------------------------------------------------------
% Project root
% -------------------------------------------------------------------------
paths.project_root = '/Volumes/ADNI/Projects/2024/ADNI/LONI_IDA/ADNI3';

% Code locations
paths.gec_code_dir = fullfile(paths.project_root, 'code', 'matlab', 'GEC_group');
paths.helpers_dir  = fullfile(paths.gec_code_dir, 'helpers');

% -------------------------------------------------------------------------
% Data locations
% -------------------------------------------------------------------------
paths.gec_data_dir = fullfile( ...
    paths.project_root, ...
    'hopf_turbu_paper_project', ...
    'main', ...
    'data', ...
    'GEC_group' ...
    );

paths.abeta_table = fullfile( ...
    paths.project_root, ...
    'participants', ...
    'cross_sectional', ...
    'ADNI3_N238rev_with_ABETA_Status_CL24.xlsx' ...
    );

% -------------------------------------------------------------------------
% Output directory
% -------------------------------------------------------------------------
paths.output_dir = fullfile( ...
    paths.project_root, ...
    'hopf_turbu_paper_project', ...
    'main', ...
    'results', ...
    'GEC_group' ...
    );

% -------------------------------------------------------------------------
% Stage-specific input files (FULL PATHS)
% -------------------------------------------------------------------------
paths.stage_files = struct();

paths.stage_files.HC = struct( ...
    'tseries_file', fullfile(paths.gec_data_dir, 'tseries_ADNI3_HC_MPRAGE_IRFSPGR_sch1000_N238rev.mat'), ...
    'f_diff_file',  fullfile(paths.gec_data_dir, 'results_f_diff_fce_cond1_ADNI3_HC_sch1000.mat'), ...
    'ptid_file',    fullfile(paths.gec_data_dir,   'PTID_ADNI3_HC_MPRAGE_IRFSPGR_all.mat'), ...
    'group_name',   'HC' ...
    );

paths.stage_files.MCI = struct( ...
    'tseries_file', fullfile(paths.gec_data_dir, 'tseries_ADNI3_MCI_MPRAGE_IRFSPGR_sch1000_N238rev.mat'), ...
    'f_diff_file',  fullfile(paths.gec_data_dir, 'results_f_diff_fce_cond1_ADNI3_MCI_sch1000.mat'), ...
    'ptid_file',    fullfile(paths.gec_data_dir,   'PTID_ADNI3_MCI_MPRAGE_IRFSPGR_all.mat'), ...
    'group_name',   'MCI' ...
    );

paths.stage_files.AD = struct( ...
    'tseries_file', fullfile(paths.gec_data_dir, 'tseries_ADNI3_AD_MPRAGE_IRFSPGR_sch1000_N238rev.mat'), ...
    'f_diff_file',  fullfile(paths.gec_data_dir, 'results_f_diff_fce_cond1_ADNI3_AD_sch1000.mat'), ...
    'ptid_file',    fullfile(paths.gec_data_dir,   'PTID_ADNI3_AD_MPRAGE_IRFSPGR_all.mat'), ...
    'group_name',   'AD' ...
    );

% -------------------------------------------------------------------------
% Structural connectivity
% -------------------------------------------------------------------------
paths.sc_file = fullfile(paths.gec_data_dir, 'schaefer_MK.mat');
end